### PR TITLE
[STYLE]: Fix Inconsistent Vertical Spacing In Hero Section on Mobile

### LINKED ISSUE #71: Section Headings’ Vertical Spacing Inconsistent on Mobile
**Describe the bug**
The vertical spacing above and below section titles (e.g. “Projects”, “DeMISTify”, “Let’s Work Together”, “Sponsor Us”, “Events”, “Careers”) varies from one section to another. This makes the layout feel uneven and misaligned.

---

**To Reproduce**

1. Open the site on mobile or desktop on any browser.
2. Scroll through the hero (“Clear The MIST”) into subsequent sections.
3. Observe that some section titles sit too close to the preceding element while others have extra gap.
4. Compare “Projects” vs “Events” vs “Careers” for uneven top/bottom margins.

---

**Expected behavior**
All section titles should have uniform top and bottom padding/margins so that the vertical rhythm is consistent across the page.

---

**Screenshots**

Image
Image
Image
Image
Image
Image

---

**Desktop (please complete the following information):**

* OS: macOS Ventura 13.5
* Browser: Chrome 115.0.5790.102

---

**Smartphone (please complete the following information):**

* Device: iPhone 12
* OS: iOS 17.5
* Browser: Safari Mobile
* Version: 17.5

---

**Additional context**
Section headings currently rely on ad-hoc margin values. Refactoring to use a consistent spacing scale (e.g. `mt-16 mb-8` for all `<h2>` on mobile) will ensure vertical rhythm is maintained.

### PR DESCRIPTION
**Pull request by williamntlam**
# Fix Inconsistent Vertical Spacing for Section Headings on Mobile
## Description
This PR standardizes the vertical spacing (margin and/or padding) above and below all major section headings (e.g., “Projects”, “DeMISTify”, “Let’s Work Together”, “Sponsor Us”, “Events”, “Careers”) across the site. The inconsistency was particularly noticeable on mobile devices, where some section titles appeared too close to or too far from adjacent content, disrupting the visual flow and layout rhythm.

### CODE REVIEW

File: client/src/components/startupsSection.tsx [hunk 1]
```diff
@@ -0,0 +1,91 @@
+import Link from "next/link";
```
Comment (KCui0327) [inline client/src/components/startupsSection.tsx:1]: This seems like it belongs to the startups PR

**Review by KCui0327 — CHANGES_REQUESTED** [review]
Good job! Just need to also align events page as well

**Comment by ambroseling** [comment]
Awesome job William, I think same for Careers page but if you think this is unrelated to this PR we can address it later
Screenshot 2025-07-05 at 10 41 18 PM

**Comment by KCui0327** [comment]
LGTM, but next PR make Startups the same format too
Screenshot 2025-07-12 at 4 36 06 PM

**Review by KCui0327 — APPROVED** [review]
